const recipesData = [
  {
    id: "banoffe",
    title: "Banoffe",
    time: "30 min",
    ingredientLines: [
      "200g bolacha maria",
      "80g manteiga",
      "Uma lata de leite condensado cozido",
      "Bananas",
      "200ml natas",
      "15g açúcar",
      "Chocolate preto para decorar",
    ],
    stepsLines: [
      "Picar a bolacha.",
      "Juntar a manteiga derretida à bolacha para forrar o fundo da tarteira e um pouco dos lados.",
      "Bater o leite condensado cozido com a batedeira para ficar uma mistura homogénea. Colocar por cima da base de bolacha.",
      "Cortar as bananas as rodelas e distribuir por cima do leite condensado cozido.Bater as natas com o açúcar até ficar firme e distribuir por cimas das bananas.",
    ],
    path: "/banoffe",
  },
  {
    id: "genoise",
    title: "Tarte de Morangos",
    time: "45 min",
    ingredientLines: [
      "4 ovos separados",
      "125g açúcar",
      "60g manteiga sem sal derretida",
      "125g farinha",
      "Morangos",
      "Açúcar",
      "Açúcar em pó para decorar",
    ],
    stepsLines: [
      "Começe por lavar bem os moragos",
      "Na batedeira, adicione as ovos e bata em velocidade baixa.",
      "Comece a adicionar o açúcar aos poucos e aumente a velocidade da batedeira.",
      "Assim que aumentar de volume, adicione a farinha peneirada.",
      "Mexa com cuidado para a massa não perder o ar das claras.",
      "Juntar a manteiga derretida, sem estar quente.",
      "Despeje a massa em uma forma forrada com papel manteiga.",
      "Asse a 200ºC por apenas 6-8 minutos.",
      "Enquanto o bolo está no forno lamine os morangos e adicione açúcar, deixe descansar, para criar uma clada",
      "Polvilhe uma superfície maleável [como um tapetinho de pano limpo] com açúcar em pó e desenforme a massa em cima.",
      "Enrole a massa delicadamente até o final",
      "Quando o bolo estiver morno desenrole, espalhe os morangos e volte a enrolar",
      "Se quiser decore com açúcar em pó",
    ],
    path: "/genoise",
  },
  {
    id: "cookies",
    title: "Cookies com recheio de nutella",
    time: "1h 30min",
    ingredientLines: [
      "200g bolacha maria",
      "80g manteiga",
      "Uma lata de leite condensado cozido",
      "Bananas",
      "200ml natas",
      "15g açúcar",
      "Chocolate preto para decorar",
    ],
    stepsLines: [
      "Picar a bolacha.",
      "Juntar a manteiga derretida à bolacha para forrar o fundo da tarteira e um pouco dos lados.",
      "Bater o leite condensado cozido com a batedeira para ficar uma mistura homogénea. Colocar por cima da base de bolacha.",
      "Cortar as bananas as rodelas e distribuir por cima do leite condensado cozido.Bater as natas com o açúcar até ficar firme e distribuir por cimas das bananas.",
    ],
    path: "/cookies",
  },
  {
    id: "brownie",
    title: "Brownie",
    time: "60 min",
    ingredientLines: [
      "200g bolacha maria",
      "80g manteiga",
      "Uma lata de leite condensado cozido",
      "Bananas",
      "200ml natas",
      "15g açúcar",
      "Chocolate preto para decorar",
    ],
    stepsLines: [
      "Picar a bolacha.",
      "Juntar a manteiga derretida à bolacha para forrar o fundo da tarteira e um pouco dos lados.",
      "Bater o leite condensado cozido com a batedeira para ficar uma mistura homogénea. Colocar por cima da base de bolacha.",
      "Cortar as bananas as rodelas e distribuir por cima do leite condensado cozido.Bater as natas com o açúcar até ficar firme e distribuir por cimas das bananas.",
    ],
    path: "/brownie",
  },
];

export default recipesData;
